version: '3.3'

services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5444:5432
    networks:
      - luizalabs
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - rabbitmq
    ports:
      - 8080:8080
    environment:
      DATASOURCE_PASSWORD: postgres
      DATASOURCE_URL: jdbc:postgresql://db:5432/
      DATASOURCE_USERNAME: postgres
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PASSWORD: teste
      RABBITMQ_USERNAME: teste
    networks:
      - luizalabs
  rabbitmq:
    build:
      context: ./rabbit
      dockerfile: Dockerfile
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "cookie"
    networks:
      - luizalabs
networks:
  luizalabs: