services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5444:5432
    networks:
      - luizalabs
  rabbitmq:
    build:
      context: ../rabbitmq
      dockerfile: Dockerfile
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "cookie"
    networks:
      - luizalabs
networks:
  luizalabs:
