spring:
  liquibase:
    change-log: classpath:db/migrations_management.xml
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate.ddl-auto: none # drop-and-create,update
    show-sql: false
    properties.hibernate.dialect: org.hibernate.dialect.PostgresPlusDialect
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST:teste}

rabbitmq:
  topic: teste-exchange
  queue: teste-queue
